project_name: cloudac-dl
release:
  github:
    owner: shahinam
    name: cloudac-dl
  draft: true
brew:
  github:
    owner: shahinam
    name: cloudac-dl
  homepage: "https://github.com/shahinam/cloudac-dl"
  description: "Downloads the video lectures for the given CloudAcademy course."
  install: bin.install "cloudac-dl"
builds:
- goos:
    - linux
    - darwin
  goarch:
    - amd64
    - "386"
  main: .
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: cloudac-dl
archive:
  format: tar.gz
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}'
  files:
    - LICENSE*
    - README*
    - CHANGELOG*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
